management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: '8088'

spring:
  main:
    allow-circular-references: 'true'
  datasource:
    hikari:
      validation-timeout: '5000'
      idle-timeout: '600000'
      maximum-pool-size: '50'
      connection-timeout: '30000'
      keepalive-time: '300000'
      max-lifetime: '1800000'
      connection-test-query: SELECT 1
      minimum-idle: '10'
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASS:juandiego21}
    username: ${DB_USER:postgres}
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/semestresdb}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'

  application:
    name: semestre-service

logging:
  level:
    org:
      hibernate:
        nodeValue: ERROR
        SQL: DEBUG
      springframework: ERROR
    root: ERROR
    web: INFO
    com:
      zaxxer:
        hikari: ERROR

app:
  api:
    version: v1
  version: 0.14.0

server:
  port: '8089'


programa-service:
  url: http://programa-service/api/v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}